from collections.abc import Sequence
from typing import Protocol

from app.domain.models import RetrievalFilters
from app.knowledge.models import IndexVersion, SearchHit, StoredUnit


class EmbeddingClient(Protocol):
    """向量客户端必须支持批量输入，避免逐条远程调用。"""

    @property
    def model_id(self) -> str: ...

    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


class KnowledgeRepository(Protocol):
    def initialize(self) -> None: ...
    def replace_document(
        self, document: dict[str, object], units: Sequence[StoredUnit]
    ) -> None: ...
    def delete_document(self, document_id: str) -> None: ...
    def get_unit(self, unit_id: str) -> StoredUnit | None: ...
    def get_units(self, unit_ids: Sequence[str]) -> list[StoredUnit]: ...
    def list_units(self, filters: RetrievalFilters | None = None) -> list[StoredUnit]: ...
    def exact_search(
        self, keys: Sequence[str], filters: RetrievalFilters, limit: int
    ) -> list[SearchHit]: ...
    def save_index_version(self, version: IndexVersion) -> None: ...
